function lbcAddControlBar() {
    var a = !1;
    if ("MENU_HOME" == _page || "MENU_BUY_LIST" == _page || "MENU_SELL_LIST" == _page || "PAGE_BUY_ONLINE_ALL" == _page || "PAGE_BUY_LOCAL_ALL" == _page || "PAGE_SELL_ONLINE_ALL" == _page || "PAGE_SELL_LOCAL_ALL" == _page || "SEARCH_BUY_ONLINE" == _page || "SEARCH_BUY_LOCAL" == _page || "SEARCH_SELL_ONLINE" == _page || "SEARCH_SELL_LOCAL" == _page) a = !0;
    var b = document.createElement("div"),
        c = _settings.showCurrencyChart ? "table-cell" : "none",
        c = "<br><div style='border: 1px solid #9999DD; border-radius: 5px; background-color: #EEEEFF;'>\t<div class='container-fluid' style='padding: 10px; color: #000000;'>\t<table style='width: 100%; table-layout: fixed;'>\t<tr>\t\t<td align='left' valign='top'>\t\t<b>Filter options:</b>\t\t<div style='background-color: #666666; width: 100%; height: 1px; margin-top: 3px; margin-bottom: 5px;'></div>\t\t<table style='width: 540px; margin-right: 10px;'>\t\t<tr>\t\t\t<td align='left' valign='center'>Limits:</td>\t\t\t<td style='padding-left: 5px;'>\t\t\t\t\t<input type='text' class='form-control text-right' placeholder='0' id='filterLimitsLow' value='" +
        _settings.limitLow + "'>\t\t\t</td>\t\t\t<td style='padding-left: 5px; padding-right: 5px;'> - </td>\t\t\t<td>\t\t\t\t\t<input type='text' class='form-control text-right' placeholder='0' id='filterLimitsHigh' value='" + _settings.limitHigh + "'>\t\t\t</td>\t\t\t<td align='right' style='padding-left: 5px; padding-right: 10px;'>\t\t\t\t<div class='btn-group'>\t\t\t\t\t<button class='btn btn-default btn-sm dropdown-toggle' type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='filterCurrency' data-value='" +
        _currency + "'>\t\t\t\t\t<span id='limitCurrency'>" + _currency + "</span> <span class='caret'></span>\t\t\t\t\t</button>\t\t\t\t\t<ul class='dropdown-menu'>\t\t\t\t\t\t<li><a href='#' onclick='lbcSelectFilterCurrency(0); return false;'><span id='limitCurrencyList'>" + _currency + "</span></a></li>\t\t\t\t\t\t<li><a href='#' onclick='lbcSelectFilterCurrency(1); return false;'>BTC</a></li>\t\t\t\t\t</ul>\t\t\t\t</div>\t\t\t</td>\t\t</tr>\t\t<tr>\t\t\t<td colspan='5'>\t\t\t<table style='width: 540px; margin-top: 22px;'>\t\t\t<tr>\t\t\t\t<td style='width: 250px;'>Show online traders only</td><td style='width: 75px;'>" +
        lbcSwitchCreator("filterOnlineOnly", null, _settings.filterOnlineOnly) + "</td><td></td>\t\t\t\t<td rowspan='4' align='right' valign='bottom' style='padding-right: 10px;'>\t\t\t\t\t<button class='btn btn-default' onclick='lbcApplyFilter();' style='margin-bottom: 5px;'>Apply filter</button>\t\t\t\t</td>\t\t\t</tr>\t\t\t<tr>\t\t\t\t<td style='width: 250px;'>Show recently active traders only</td><td style='width: 75px;'>" + lbcSwitchCreator("filterRecentOnly", null, _settings.filterRecentOnly) + "</td><td></td>\t\t\t</tr>\t\t\t<tr>\t\t\t\t<td style='width: 250px;'>Show trusted traders only</td><td style='width: 75px;'>" +
        lbcSwitchCreator("filterTrustedOnly", null, _settings.filterTrustedOnly) + "</td><td></td>\t\t\t</tr>\t\t\t<tr>\t\t\t\t<td style='width: 250px;'>Hide traders with negative feedback</td><td style='width: 75px;'>" + lbcSwitchCreator("filterHideNegative", null, _settings.filterHideNegative) + "</td><td></td>\t\t\t</tr>\t\t\t</table>\t\t\t</td>\t\t</tr>\t\t</table>\t\t</td>\t\t<td align='left' valign='top' id='lbcChart' style='width: 230px; display: " + c + "; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;'>\t\t<b>BTC / <span id='chartCurrency'>" +
        _currency + "</span> chart:</b>\t\t<div style='background-color: #666666; width: 100%; height: 1px; margin-top: 3px; margin-bottom: 5px;'></div>\t\t<table>\t\t<tr>\t\t\t<td>\t\t\t<a id='lbcChartLink' href='http://bitcoinity.org/markets/localbitcoins/" + _currency + "' target='_blank'>\t\t\t\t<img style='height: 137px; width: 220px;' id='lbcChartImg' src='" + _prot + "//bitcoinity.org/markets/image?span=24h&size=medium&currency=" + _currency + "&exchange=localbitcoins'>\t\t\t</a>\t\t\t</td>\t\t</tr>\t\t</table>\t\t</td>\t\t<td align='left' valign='top' style='width: 250px;'>\t\t<b>Settings:</b>\t\t<div style='background-color: #666666; width: 100%; height: 1px; margin-top: 3px; margin-bottom: 5px;'></div>\t\t<table>\t\t<tr>\t\t\t<td style='width: 170px;'>Show detailed results</td><td style='width: 75px;'>" +
        lbcSwitchCreator("showDetailedResults", lbcShowHideList, _settings.showDetailedResults) + "</td>\t\t</tr>\t\t<tr>\t\t\t<td style='width: 170px;'>Load trader details</td><td style='width: 75px;'>" + lbcSwitchCreator("loadTraderDetails", lbcLoadUserInfo, _settings.loadTraderDetails) + "</td>\t\t</tr>\t\t<tr>\t\t\t<td style='width: 170px;'>Load trader feedback</td><td style='width: 75px;'>" + lbcSwitchCreator("loadTraderFeedback", lbcLoadUserInfo, _settings.loadTraderFeedback) + "</td>\t\t</tr>\t\t<tr>\t\t\t<td style='width: 170px;'>Hide suspicious traders</td><td style='width: 75px;'>" +
        lbcSwitchCreator("hideSuspiciousTraders", lbcShowHideList, _settings.hideSuspiciousTraders) + "</td>\t\t</tr>\t\t<tr>\t\t\t<td style='width: 170px;'>Keep my online status</td><td style='width: 75px;'>" + lbcSwitchCreator("keepMeActive", lbcKeepMeOnline, _settings.keepMeActive) + "</td>\t\t</tr>\t\t<tr>\t\t\t<td style='width: 170px;'>Show currency chart</td><td style='width: 75px;'>" + lbcSwitchCreator("showCurrencyChart", lbcShowChart, _settings.showCurrencyChart) + "</td>\t\t</tr>\t\t<tr>\t\t\t<td style='width: 170px;'>Show filtered results</td><td style='width: 75px;'>" +
        lbcSwitchCreator("showFilter", lbcShowFilteredResults, _settings.showFilter) + "</td>\t\t</tr>\t\t</table>\t\t</td>\t</tr>\t</table>\t<table style='width: 100%; table-layout: fixed; display: none;' id='progressbar-table'>\t<tr>\t\t<td>\t\t\t<div class='progress' id='progressbar' style='margin-bottom: 0px; margin-top: 15px'>\t\t\t\t<div class='progress-bar' role='progressbar' aria-valuenow='60' aria-valuemin='0' aria-valuemax='100' style='width: 0%;' id='modal-progressbar'>0%</div>\t\t\t</div>\t\t\t<div id='progress-info' style='; font-weight: normal;'></div>\t\t</td>\t</tr>\t</table>\t</div></div>";
    b.innerHTML = c;
    a && ((a = document.body.querySelector('div[class="search-form-wrap"]')) ? lbcInsertAfter(a, b) : document.body.querySelectorAll('div[class="container"]')[1] && document.body.querySelectorAll('div[class="container"]')[1].children[1] ? (a = document.body.querySelectorAll('div[class="container"]')[1].children[1], lbcInsertAfter(a, b)) : document.getElementById("result-count") && (a = document.getElementById("result-count"), lbcInsertBefore(a, b)))
};